# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
c =np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.reshape(c, (2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)
b = b.astype('int32')

In [4]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [5]:
a = np.arange(10).reshape(2,5)
b = np.ones(10).reshape(2,5)
b = b.astype('int32')

In [6]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [7]:
q = ([[0,1,2,3,4],[5,6,7,8,9]])
np.ravel(q)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
array = np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]])
array.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [9]:
d = np.arange(15)
np.reshape(d,(5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [10]:
f = np.arange(30,55)
f.reshape(5,5)

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [11]:
np.square(f)

array([ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600,
       1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601,
       2704, 2809, 2916], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [12]:
x = np.arange(20,50).reshape(5,6)
np.mean(x)

34.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [13]:
np.std(x)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [14]:
np.median(x)

34.5

## Question:11

### Find the transpose of the previous array in Q8?

In [15]:
np.transpose(x)

array([[20, 26, 32, 38, 44],
       [21, 27, 33, 39, 45],
       [22, 28, 34, 40, 46],
       [23, 29, 35, 41, 47],
       [24, 30, 36, 42, 48],
       [25, 31, 37, 43, 49]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [16]:
y = np.arange(16).reshape(4,4)
np.diagonal(y)

array([ 0,  5, 10, 15])

## Question:13

### Find the determinant of the previous array in Q12?

In [17]:
np.linalg.det(y)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [18]:
p = np.arange(25,50)
np.percentile(p,5)

26.200000000000003

In [19]:
np.percentile(p,95)

47.8

## Question:15

### How to find if a given array has any null values?

In [72]:
n = np.array([[0,1,2],[3,5,6],[7,8,9]],dtype='float')
n[1,1]=np.nan
np.isnan(n)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])